### ISSUE TITLE
Can potree-core run on cesium?

### ISSUE THREAD

**Issue by khomsun2013** [tentone/potree-core#1]
I want to do a project that run potree on Cesium without potree viewer. By using Cesium as the main rendering similar to this example (http://potree.org/potree/examples/cesium_ca13.html). What are the modules that I should add on potree-core to rendering properly on Cesium?

**Comment by tentone** [comment]
Hi

Potree should be able to run within a totally normal threejs project, you have to use the hole thing. (Use the minified build). (https://cesium.com/blog/2017/10/23/integrating-cesium-with-threejs/).

Cumps

**Comment by khomsun2013** [comment]
Hi

Thanks for your suggestion. I tried with the minified build(https://cesium.com/blog/2017/10/23/integrating-cesium-with-threejs/). It wasn't work. 
This is some parts of my codes.
points.add(pointcloud);
var geometry = new THREE.LatheGeometry(points);
var latheMesh = new THREE.Mesh(geometry, points.material ) ;
var latheMeshYup = new THREE.Group();
    latheMeshYup.add(latheMesh);
    three.scene.add(latheMeshYup); 
    
    var _3DOB = new _3DObject();
    _3DOB.threeMesh = latheMeshYup;
    _3DOB.minWGS84 = minWGS84;
    _3DOB.maxWGS84 = maxWGS84;
    _3Dobjects.push(_3DOB);
    three.scene.add(points); 
I create  points from Potree.Group  (var points = new Potree.Group();), and var geometry = new THREE.LatheGeometry(points). I don't know what are wrong.

Khomsun
