### ISSUE TITLE
Not working in Firefox: "document.currentScript is null"

### ISSUE THREAD

**Issue by leefsmp** [tentone/potree-core#10]
Working perfectly in Chrome and Safari, getting following error in Firefox:

<img width="428" alt="Screen Shot 2019-10-13 at 14 02 51" src="https://user-images.githubusercontent.com/4352502/66715316-5363d280-edc2-11e9-904b-9dce4081a71c.png">

OS: MacOS High Sierra 10.13.3

**Comment by tentone** [comment]
Hello

It should be supported by FF https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

I will take a look at it, thanks a lot for reporting this bug.

**Comment by tentone** [comment]
Seems to be working without any errors on firefox. Can you please provide some additional details?

![adad](https://user-images.githubusercontent.com/9158354/66716978-e8b79480-edcb-11e9-87f8-24349e4eb52f.PNG)

**Comment by leefsmp** [comment]
I'm using webpack if that makes any difference... the demo at https://tentone.github.io/potree-core is also working in FF on my side.

**Comment by tentone** [comment]
Yeah that is possible the problem anyway you can override the location of the workers on the `Potree.Global.workerPath` attribute.

Just set it to the path where you have the decode workers.

**Comment by leefsmp** [comment]
Doing that already:

    import {
      loadPointCloud,
      PointColorType,
      PointSizeType,
      PointShape,
      Global,
      Group
    } from 'potree-core/build/potree.module'

    const PotreeCore = {
      loadPointCloud,
      PointColorType,
      PointSizeType,
      PointShape,
      Global,
      Group
    }

   // ...

   initialize () {
   
     // ... 
     PotreeCore.Global.workerPath = '/resources/potree' //contains folder /workers
   }

**Comment by tentone** [comment]
I have added an additional check to make sure that the currentScript exists before using it. Should be enough to prevent the error.

You will still need to set the workerPath pointing to the correct location (relative to your doc path or web server root)

**Comment by leefsmp** [comment]
Working now, thanks a lot for your prompt replies and the great lib!

**Comment by tentone** [comment]
No problem happy to be of use. Thanks a lot for reporting the problem.
