### ISSUE TITLE
logarithmicDepthBuffer: true throws error

### ISSUE THREAD

**Issue by shiukaheng** [tentone/potree-core#12]
I've tested the issue using the given example, but it throws an error. Using Google Chrome | 77.0.3865.120 (Official Build) (64-bit) (cohort: Stable)
![Capture](https://user-images.githubusercontent.com/31088159/67797088-13b31100-fa79-11e9-95be-65e94a7a3e3e.PNG)
![Capture2](https://user-images.githubusercontent.com/31088159/67797089-13b31100-fa79-11e9-932c-0ca3165ab6c5.PNG)
Thanks,
Heng

**Comment by tentone** [comment]
Hello

I was able to replicate this issue with the last version of threejs. Should be due to changes in the logarithmic depth shaders.

I will take a look at it.

Thank you.

**Comment by tentone** [comment]
Should  be fixed now.

Thanks a lot for reporting!
