### ISSUE TITLE
Point don't appear in React

### ISSUE THREAD

**Issue by TheRomanOne** [tentone/potree-core#18]
I have a pointcloud data created with `PotreeConverter` that i want to load with `potree-core` in a `THREEjs` scene.

when I run the scene as is, from a `flask` backend everything works, I have a point cloud and a bbox around it.
but when the scene is wrapped around a `React` component, the bbox is rendered but not the points

any reason it should act like this? from what I understand react is rendered on a shadowDOM which is separates from the original DOM, maybe it has something to do with it?

**Comment by TheRomanOne** [comment]
Had to modify `PotreeCore.Global.workerPath`. now it works

**Comment by tentone** [comment]
Hello

I'm sorry o completely missed this issue.

Happy that you figured it out on your own. The path to the workers used needs to be set manually when it is changed.

Thanks a lot

Cheers
