### ISSUE TITLE
Material pointColorType and gradient does nothing

### ISSUE THREAD

**Issue by arjan-kuiper** [tentone/potree-core#25]
I want to change how my pointcloud is colored by changing the pointColorType. I've tried all possible types, but the pointcloud doesn't change in color. It just stays in RGB. Elevation. intensity, etc. are not doing anything. I've also tried multiple gradients, but none of them change anything.

Am I missing something or is it broken?

**Comment by tentone** [comment]
Hello

These were removed from the library, only color is supported for this lib.

Thank you

**Comment by bethanywallace** [comment]
> Hello
> 
> These were removed from the library, only color is supported for this lib.
> 
> Thank you

Hi, does this include the map attribute? As in the ability to use an image as a texture over the point cloud? TIA

**Comment by tentone** [comment]
Only point color is supported by the library currently.
