### ISSUE TITLE
Can't load octree from protected storage

### ISSUE THREAD

**Issue by vadzim-rakevich-softensity** [tentone/potree-core#26]
Cannot add sas token when trying to download hierarchy.bin and octree.bin files. 

I guess passing 'xhrRequest' param [here](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L496) and replacing 'fetch' with 'xhrRequest' when loading [octree](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L63) and [hierarchy](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L284) would fix the problem. 

Another possible solution is to check how the path to octree.bin and hierarchy.bin is [formed](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L49) . Replacing `${this.url}/../octree.bin` with `${this.url}.replace('/metadata.json' ,'/octree.bin')` would solve the problem in my case.

Thanks.

**Comment by tentone** [comment]
Hello

For wich version of the lib is this happening?

The current master or the under works 2.0?

Thanks a lot!

**Comment by vadzim-rakevich-softensity** [comment]
Hi

I am using potree-core 2.0.3. I guess it is current master.

Thanks.

**Comment by tentone** [comment]
Since you already have a proposel to solve the issue feel free to open a PR to apply the changes suggested.

If you prefer i can do it myself but since you have already have prepared this you can go ahead

Thanks a lot once again!

**Comment by hamza-iqbal-ad** [comment]
> Cannot add sas token when trying to download hierarchy.bin and octree.bin files.
> 
> I guess passing 'xhrRequest' param [here](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L496) and replacing 'fetch' with 'xhrRequest' when loading [octree](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L63) and [hierarchy](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L284) would fix the problem.
> 
> Another possible solution is to check how the path to octree.bin and hierarchy.bin is [formed](https://github.com/tentone/potree-core/blob/5d18c0626ea264e8cf4f8b7a871a8b6dbd84b5fc/source/loading2/OctreeLoader.ts#L49) . Replacing `${this.url}/../octree.bin` with `${this.url}.replace('/metadata.json' ,'/octree.bin')` would solve the problem in my case.
> 
> Thanks.

Replacing the filename doesnt work for s3 presigned urls because the url are completely different from each other.
I am stuck on this issue, can someone please resolve this blocker?

**Comment by tentone** [comment]
Hello

We can maybe include a costumizable file retrieve system that can be adapted for you scenario.

But this can also be solved on your side with a intermediary piece of software that converts these.

**Comment by im-hamza-dev** [comment]
I have resolved the issue for now by overriding my window.fetch function and replacing the octree.bin url with the correct one like this:

` const nativeFetch = window.fetch;

    window.fetch = function (...args) {

      if (args[0].toString().includes('hierarchy.bin')) {

        args[0] = urls.hierarchy;

      } else if (args[0].toString().includes('octree.bin')) {

        args[0] = urls.octree;

      } else if (args[0].toString().includes('metadata.json')) {

        args[0] = urls.metadata;

      }

      return nativeFetch.apply(window, args);

    };`
