### ISSUE TITLE
Including Potree-Core breaks SSR

### ISSUE THREAD

**Issue by Archimagus** [tentone/potree-core#42]
When including Potree Core in an application that uses Server Side Rendering a `ReferenceError: document is not defined` is generated.

This is caused by `features.ts` using the `document` in the root of the file so there is no way to prevent it from being called on the server side.

A proposed fix is PR #41

Alternatively, Features seems like it could be removed as it doesn't seem to be used in the code anywhere?

**Comment by tentone** [comment]
Hello

Thanks a lot for the contribution!

It has been merged into the codebase.

Will publish a new version soon to npm!

**Comment by Archimagus** [comment]
Hey, about when do you think you might get a new NPM package up?  Thanks.
