### ISSUE TITLE
Potree-core not working with SSR 

### ISSUE THREAD

**Issue by Haxersociety** [tentone/potree-core#45]
[https://github.com/tentone/potree-core/issues/42](https://github.com/tentone/potree-core/issues/42)
There was 42 issue with same problem, in last 2.0.8 version part problem was resolved, but in function generateGradientTexture again used 'document', which broken SSR.

[https://github.com/tentone/potree-core/blob/238198bfb1d7c13fbe852e63967ef20f995675f3/source/materials/texture-generation.ts#L39](https://github.com/tentone/potree-core/blob/238198bfb1d7c13fbe852e63967ef20f995675f3/source/materials/texture-generation.ts#L39)

Error: ReferenceError: document is not defined

**Comment by Haxersociety** [comment]
[PR](https://github.com/tentone/potree-core/pull/46)
This PR fixed problem

**Comment by tentone** [comment]
Thanks a lot

Merged the PR
