### ISSUE TITLE
Point cloud coordinates

### ISSUE THREAD

**Issue by jvntf** [tentone/potree-core#6]
Hey thanks for your great work with this!
I am having a problem loading a pointcloud within a threeJS scene.
I am using `threeJS` with `potree-core` to create a `Mapbox Custom Layer` that I am applying to a map rendered by `react-map-gl`
I am able to load pointclouds that in generic XYZ identity coordinates and show them on my map, but when I try to load pointclouds that contain geographic data (both in UTM projection and in WGS84 lat / lon) the cloud does not render correctly. 
Any idea of what I am doing wrong?

**Comment by tentone** [comment]
Hi

The library does not support geographic encoded data, they need to be converted to XYZ cartographic coordinates.

I would like to add support for these to the library its possible for you to shale one example encoded in each format alonside with a XYZ one for validation?

Thanks a lot.
