### ISSUE TITLE
blue outline on adaptive sized points

### ISSUE THREAD

**Issue by JulianRuiseco** [tentone/potree-core#7]
I have been digging in on why this blue outline appears on the points.

I would be happy to work on maintaining the project if you can point me in the right direction.

![image](https://user-images.githubusercontent.com/45122130/62236839-db2e6900-b39d-11e9-82bf-f4c03c939287.png)

**Comment by tentone** [comment]
Hi

The outside line should be the color of these points.

Check if you have the color mode set to RGB in the point cloud material.

When converting from textural formats to potree sometimes it is necessary to check for color ordering and scale that could also be the reason for these colors.

Thanks a lot.
